name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Increase this if needed
    
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest src/test_addition.py  # Run test file inside src
