name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH (Fix Import Error)
      run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

    - name: Verify File Structure
      run: ls -R  # Debugging step to check if files exist

    - name: Run tests
      run: pytest src/test_addition.py
