name: Python Tests

on: [push]  # Runs on every push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Pulls latest code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        if [ -d "src" ]; then cd src; fi  # Only cd if src exists
        pytest  # Runs all test files automatically
